name: "Continuous Integration"

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      php-versions:
        description: "The PHP versions to use when running the job"
        default: "['7.4', '8.0', '8.1']"
        required: false
        type: "string"
      php-extensions:
        description: "The php extensions to install, allowing composer to pass"
        default: "none, ctype, dom, json, mbstring, phar, simplexml, tokenizer, xml, xmlwriter, fileinfo"
        required: false
        type: "string"
      composer-root-version:
        description: "The version of the package being tested, in case of circular dependencies."
        required: false
        type: "string"
      composer-options:
        description: "Additional flags for the composer install command."
        default: "--prefer-dist"
        required: false
        type: "string"
      test-suite:
        description: "Test suite to run"
        default: "unit"
        required: false
        type: "string"

jobs:
  tests:
    name: "Tests"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version: "${{ fromJson(inputs.php-versions) }}"
        dependencies:
          - "lowest"
          - "locked"
          - "highest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Set up PHP"
        uses: "shivammathur/setup-php@2.25.4"
        with:
          coverage: "none"
          extensions: "${{ inputs.php-extensions }}"
          php-version: "${{ matrix.php-version }}"

      - name: "Set COMPOSER_ROOT_VERSION"
        run: |
          echo "COMPOSER_ROOT_VERSION=${{ inputs.composer-root-version }}" >> $GITHUB_ENV
        if: "${{ inputs.composer-root-version }}"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "${{ inputs.composer-dependencies }}"
          composer-options: "${{ inputs.composer-options }}"
          # Bust the cache at least once a month - output format: YYYY-MM.
          custom-cache-suffix: $(date -u "+%Y-%m")

      - name: "Run tests with phpunit/phpunit"
        run: "vendor/bin/phpunit --colors=always --testsuite=${{ inputs.test-suite }}"
