name: "Documentation"

on: # yamllint disable-line rule:truthy
  workflow_call:

env:
  REGISTRY: "ghcr.io"

jobs:
  documentation:
    name: "Documentation"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Render Documentation"
        uses: "docker://phpdoc/phpdoc:latest"
        with:
          args: "run --config-file=phpdoc.dist.xml"

      - name: "Prepare docker image"
        run: |
          echo ":80" > build/docs/Caddyfile
          echo "file_server {" >> build/docs/Caddyfile
          echo "  root /data"  >> build/docs/Caddyfile
          echo "}" >> build/docs/Caddyfile

          echo "FROM caddy:2-alpine" > build/docs/Dockerfile
          echo "COPY Caddyfile /etc/caddy/Caddyfile" >> build/docs/Dockerfile
          echo "COPY . /data" > build/docs/Dockerfile

      - name: "Prepare image name"
        run: |
          echo IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

      - name: "Set up QEMU"
        uses: "docker/setup-qemu-action@v3"

      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v3"

      - name: "Login to Docker Hub"
        uses: "docker/login-action@v3"
        with:
          registry: "${{ env.REGISTRY }}"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Build and push"
        uses: "docker/build-push-action@v5"
        with:
          context: "build/docs"
          push: true
          tags: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
