name: "Lint"

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      php-version:
        description: "The PHP version to use when running the job"
        default: "8.0"
        required: false
        type: "string"
      php-extensions:
        description: "The php extensions to install, allowing composer to pass"
        default: "none, ctype, dom, json, mbstring, phar, simplexml, tokenizer, xml, xmlwriter, fileinfo"
        required: false
        type: "string"
      composer-options:
        description: "Additional flags for the composer validate command."
        default: "--ansi --strict"
        required: false
        type: "string"
      composer-file:
        description: "Composer file to validate."
        default: "composer.json"
        required: false
        type: "string"
jobs:

  lint:
    name: "Lint yaml & Composer"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "${{ inputs.php-version }}"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Lint YAML files"
        uses: "ibiqlik/action-yamllint@v3.1"
        with:
          config_file: ".yamllint.yaml"
          file_or_dir: "."
          strict: true

      - name: "Set up PHP"
        uses: "shivammathur/setup-php@2.34.0"
        with:
          coverage: "none"
          extensions: "${{ inputs.php-extensions }}"
          php-version: "${{ matrix.php-version }}"

      - name: "Validate composer.json and composer.lock"
        run: "composer validate ${{ inputs.composer-options }} ${{ inputs.composer-file }}"
